[package]
name = "neophyte-ui-event"
version = "0.3.1"
edition = "2021"
authors = ["Tim Harding"]
repository = "https://github.com/tim-harding/neophyte"
license = "MIT"
keywords = ["neovim"]
description = "Parsing for Neovim UI events"

[dependencies]
rmpv = "1.0.1"
thiserror = "2.0.1"
